//     ▄▄ ▄▄ ▄▄  ▄▄▄▄  ▄▄▄▄ ▄▄    ▄▄▄▄▄ ▄▄▄▄
//     ██ ██ ██ ██ ▄▄ ██ ▄▄ ██    ██▄▄  ██▄█▄   Copyright (c) 2026 Julian Storer
//   ▄▄█▀ ▀███▀ ▀███▀ ▀███▀ ██▄▄▄ ██▄▄▄ ██ ██   AGPL-3.0-or-later - see LICENSE

package worker

import (
	"encoding/json"
	"fmt"
	"strings"
)

// ContextResult holds the system prompt and context item contexts from the frontend.
type ContextResult struct {
	SystemPrompt string
	Contexts     []ItemContext
}

// requestContextAndTools requests context and tool definitions from the browser
// in parallel, waiting for both responses in a single wait loop. This eliminates
// the latency of sequential round-trips.
func (w *ConversationWorker) requestContextAndTools() (*ContextResult, []ToolDefinition, error) {
	itemIDs := w.doc.GetContextItemIDsForThread(w.getProcessingThreadItemID())

	if len(itemIDs) > 0 {
		// Pin the requestId so only the reply to THIS request is accepted as
		// this turn's context (handleRenderContextItemsResponse drops the rest).
		rid := generateRequestID()
		w.expectedContextRequestID = rid
		defer func() { w.expectedContextRequestID = "" }()
		w.sendRenderContextItemsRequest(rid, itemIDs)
	}
	w.send(map[string]any{
		"type":      "request-tools",
		"requestId": generateRequestID(),
	})

	needContext := len(itemIDs) > 0
	ctxRaw, toolsRaw, err := w.waitForContextAndTools(ContextTimeout, needContext)
	if err != nil {
		return nil, nil, err
	}

	ctxResult := &ContextResult{}
	if ctxRaw != nil {
		var ctxMsg RenderContextItemsResponse
		if err := json.Unmarshal(ctxRaw, &ctxMsg); err != nil {
			return nil, nil, fmt.Errorf("context response: %w", err)
		}
		ctxResult.SystemPrompt = ctxMsg.SystemPrompt
		ctxResult.Contexts = ctxMsg.Contexts
	}

	var toolsMsg ToolsResultMessage
	if err := json.Unmarshal(toolsRaw, &toolsMsg); err != nil {
		return nil, nil, fmt.Errorf("tools response: %w", err)
	}

	return ctxResult, toolsMsg.Tools, nil
}

// buildLLMRequest constructs the LLM request payload. txnID is generated by
// the caller (runStrategyLoop) so the same id is used for the request, the
// blob filename, and the stamping of items inserted during the round-trip.
func (w *ConversationWorker) buildLLMRequest(ctxResult *ContextResult, tools []ToolDefinition, txnID string) json.RawMessage {
	messages := w.buildMessages(ctxResult.Contexts)
	systemPrompt := w.buildSystemPrompt(ctxResult.SystemPrompt, ctxResult.Contexts)

	request := map[string]any{
		"type":           "message",
		"systemPrompt":   systemPrompt,
		"messages":       messages,
		"tools":          tools,
		"conversationId": w.conversationID,
		// threadId scopes the provider session to THIS thread: each thread gets
		// its own CLI/session instance (own warm prompt cache), so switching
		// threads no longer thrashes one shared session. "" = the root thread.
		"threadId":      w.thread.itemID,
		"modelConfig":   w.resolveModelConfig(),
		"transactionId": txnID,
	}

	// A plugin may force a specific tool for this thread's turns (e.g. /compact
	// forces return_result). Honour it generically: translate the thread's
	// forceTool field into a provider-agnostic toolChoice that the server hands
	// to the provider. Only emitted when the forced tool is actually offered
	// this turn, so we never send an API-invalid choice.
	if tc := w.resolveForcedToolChoice(tools); tc != nil {
		request["toolChoice"] = tc
	}

	data, _ := json.Marshal(request)
	return data
}

// resolveForcedToolChoice reads the current thread's `forceTool` Yjs field (set
// by a plugin) and, when present AND the named tool is among this turn's tools,
// returns the provider-agnostic toolChoice the server forwards to the provider.
// Returns nil for the normal case (no force, or the forced tool isn't offered),
// leaving tool selection to the model.
func (w *ConversationWorker) resolveForcedToolChoice(tools []ToolDefinition) map[string]any {
	if w.thread.itemID == "" {
		return nil
	}
	threadYMap := w.doc.GetThreadYMap(w.thread.itemID)
	if threadYMap == nil {
		return nil
	}
	ycrdtMu.Lock()
	forceTool, _ := threadYMap.Get("forceTool").(string)
	ycrdtMu.Unlock()
	if forceTool == "" {
		return nil
	}
	offered := false
	for _, t := range tools {
		if t.Name == forceTool {
			offered = true
			break
		}
	}
	if !offered {
		w.log.Info("[worker] thread forces tool %q but it is not offered this turn — ignoring", forceTool)
		return nil
	}
	return map[string]any{"mode": "tool", "name": forceTool}
}

// buildUserMessageMap returns a user message map carrying the item's text
// content plus, when the item has attachments, an image "parts" array (one
// entry per attachment referencing the asset by id). The server resolves each
// assetId to bytes at the LLM-call boundary. Only user messages carry parts.
func buildUserMessageMap(item ConversationItem) map[string]any {
	m := map[string]any{"type": "user", "content": item.Content}
	if len(item.Attachments) > 0 {
		parts := make([]map[string]any, 0, len(item.Attachments))
		for _, att := range item.Attachments {
			parts = append(parts, map[string]any{
				"type":    "image",
				"mime":    att.Mime,
				"assetId": att.ID,
				"width":   att.Width,
				"height":  att.Height,
			})
		}
		m["parts"] = parts
	}
	return m
}

// buildToolUseMap returns a tool-use message map from the item's tool fields.
func buildToolUseMap(item ConversationItem) map[string]any {
	var toolInput map[string]any
	if item.ToolInput != nil {
		_ = json.Unmarshal(item.ToolInput, &toolInput)
	}
	m := map[string]any{
		"type":      "tool-use",
		"toolUseId": item.ToolUseID,
		"toolName":  item.ToolName,
		"toolInput": toolInput,
	}
	if len(item.ProviderData) > 0 {
		m["providerData"] = item.ProviderData
	}
	return m
}

// buildToolResultMap returns a tool-result message map from the item's Result JSON.
// Returns nil if the result cannot be unmarshalled.
func buildToolResultMap(item ConversationItem) map[string]any {
	var result map[string]any
	if err := json.Unmarshal(item.Result, &result); err != nil {
		return nil
	}
	content, _ := result["content"].(string)
	isError, _ := result["isError"].(bool)
	return map[string]any{
		"type":      "tool-result",
		"toolUseId": item.ToolUseID,
		"content":   content,
		"isError":   isError,
	}
}

// buildThreadResultMap returns a thread result as an assistant message, or nil if no result.
func buildThreadResultMap(item ConversationItem) map[string]any {
	result := threadResultString(item)
	if result == "" {
		return nil
	}
	return map[string]any{
		"type": "assistant",
		"content": fmt.Sprintf("[Completed Thread: %s]\nThis work has been completed by a sub-thread — do not repeat it:\n\n%s",
			item.Goal, result),
	}
}

// buildThreadToolResultMap returns the user-side tool_result for an
// LLM-spawned thread. Used when the thread item carries the toolUseID of the
// create_thread call that produced it — the paired tool_use block is emitted
// separately via buildToolUseMap.
func buildThreadToolResultMap(item ConversationItem) map[string]any {
	result := threadResultString(item)
	if result == "" {
		return nil
	}
	return map[string]any{
		"type":      "tool-result",
		"toolUseId": item.ToolUseID,
		"content":   fmt.Sprintf("[Completed Thread: %s]\n%s", item.Goal, result),
		"isError":   false,
	}
}

// appendThreadMessages emits messages for a thread item. For LLM-spawned
// threads with a fully-recorded tool call (ToolUseID + ToolName + ToolInput)
// it emits the assistant tool_use + user tool_result pair so the parent
// LLM sees its own create_thread call. For user/strategy-created threads, or
// thread items lacking ToolInput on the Y.Map, it emits an assistant summary
// instead — an Anthropic tool_use with null input is silently dropped by the
// provider, so the summary is the safer wire shape when input wasn't recorded.
func appendThreadMessages(messages []map[string]any, item ConversationItem) []map[string]any {
	if item.ToolUseID != "" && item.ToolName != "" && len(item.ToolInput) > 0 {
		messages = append(messages, buildToolUseMap(item))
		if rm := buildThreadToolResultMap(item); rm != nil {
			messages = append(messages, rm)
		}
		return messages
	}
	if m := buildThreadResultMap(item); m != nil {
		messages = append(messages, m)
	}
	return messages
}

// buildMessages converts conversation items to LLM message format.
// Uses provider.Message format with discriminated union via Type field.
func (w *ConversationWorker) buildMessages(contexts []ItemContext) []map[string]any {
	var messages []map[string]any

	items := w.getTargetItems()

	for i := 0; i < len(items); i++ {
		item := items[i]
		switch item.Type {
		case ItemTypeUser:
			messages = append(messages, buildUserMessageMap(item))

		case ItemTypeAssistant:
			messages = append(messages, map[string]any{"type": "assistant", "content": item.Content})

		case ItemTypeThinking:
			messages = append(messages, map[string]any{"type": "thinking", "content": item.Content})

		case ItemTypeToolAction:
			// Collect consecutive tool-action items so tool_use
			// messages are batched before tool_result messages.
			// transformMessages groups consecutive tool_use items
			// into one assistant message (with reasoning_content
			// replayed via EchoReasoningContent). Interleaving
			// tool_use/tool_result pairs would produce separate
			// assistant messages — only the first gets the
			// reasoning_content, causing DeepSeek's thinking mode
			// to 400: "The reasoning_content ... must be passed
			// back to the API."
			end := i + 1
			for end < len(items) && items[end].Type == ItemTypeToolAction {
				end++
			}
			toolActions := items[i:end]

			// Emit all tool_use messages first.
			for _, ta := range toolActions {
				if ta.ToolUseID == "" || ta.ToolName == "" {
					w.log.Error("[Worker] WARNING: Tool action skipped - ToolUseID=%q, ToolName=%q", ta.ToolUseID, ta.ToolName)
					continue
				}
				messages = append(messages, buildToolUseMap(ta))
			}

			// Emit tool_result messages.
			for _, ta := range toolActions {
				if ta.ToolUseID == "" || ta.ToolName == "" {
					continue
				}
				// Tool may not have finished yet if auto-continue raced ahead
				// of tool execution completing. Emit an explicit isError
				// tool-result so the LLM treats it as a failure rather than
				// fabricating reasoning from a misleading "in progress" body.
				// The strategy loop will re-trigger when the tool finishes;
				// shipping a lying success body here is the worse outcome.
				if ta.State != StateCompleted && ta.State != StateCancelled {
					w.log.Error("WARNING: Tool %s has no result yet — emitting isError tool-result (auto-continue may have raced ahead of execution)", ta.ToolUseID)
					messages = append(messages, map[string]any{
						"type":      "tool-result",
						"toolUseId": ta.ToolUseID,
						"content":   "[internal] Tool execution did not complete before message build. Do not fabricate output — wait for the actual result.",
						"isError":   true,
					})
					// We just delivered a (placeholder) result for a tool still in
					// state=running. Stamp the current turn so a mid-turn engine reattach
					// does NOT reset+re-execute it — the resultFedTurn CURE that removes the
					// duplicate re-feed at source (doc.go's "Tool-delivery desync" section,
					// claudecode provider). The stamp self-expires (a later turn carries a
					// higher turnCounter), so a genuinely-stuck tool can still be recovered
					// by a future reattach. Store as int: y-crdt's YMap.Set accepts Number
					// (=int), and convertToYcrdt leaves an int64 untyped for it (see its
					// float64 case). resetRunningToolsForReattach reads it back numerically.
					w.doc.UpdateToolActionFieldsRecursive(ta.ToolUseID, map[string]any{
						"resultFedTurn": int(w.docTurnCounter()),
					})
					continue
				}

				if rm := buildToolResultMap(ta); rm != nil {
					messages = append(messages, rm)
				} else {
					w.log.Error("FATAL: Tool %s Result unmarshal failed", ta.ToolUseID)
					messages = append(messages, map[string]any{
						"type":      "tool-result",
						"toolUseId": ta.ToolUseID,
						"content":   "ERROR: Invalid result JSON",
						"isError":   true,
					})
				}
			}

			// Advance past the batch we just consumed (-1 because the loop increments).
			i = end - 1

		case ItemTypeThread:
			messages = appendThreadMessages(messages, item)

		case ItemTypeMetaToolResult:
			if item.ToolName != "" {
				messages = append(messages, buildToolUseMap(item))
			}
			if item.Result != nil {
				if rm := buildToolResultMap(item); rm != nil {
					messages = append(messages, rm)
				}
			}

		case ItemTypeSystemReminder, ItemTypeGuidance:
			// Strategy-injected meta-instruction (injectGuidance). Emitted
			// verbatim; the provider maps it to the user role. Mirrors the
			// context-builder fallback, which passes both types through.
			if item.Content != "" {
				messages = append(messages, map[string]any{"type": item.Type, "content": item.Content})
			}
		}
	}

	return messages
}

// buildSystemPrompt constructs the system prompt with context.
// The base system prompt is provided by the frontend (via SystemPromptType.buildPrompt()).
// This function appends context item contexts (contextPosition !== 'system') to the base prompt.
func (w *ConversationWorker) buildSystemPrompt(basePrompt string, contexts []ItemContext) string {
	var prompt strings.Builder
	prompt.WriteString(basePrompt)

	// Context items with non-system position are appended here; system-position
	// items (rules etc.) are already in basePrompt from the frontend.
	for _, ctx := range contexts {
		if ctx.Content != "" {
			fmt.Fprintf(&prompt, "\n\n=== Context: %s ===\n%s", ctx.ItemID, ctx.Content)
		}
	}

	return prompt.String()
}
